---
name: CI Build

on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Save current weather condition
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          FILE=./docs/assets/data/`date +"%Y%m%d"`.json
          if [ -f "$FILE" ]; then
              echo "$FILE exists. Done for today."
          else
              echo "Begin to get today's weather condition."
              url="https://api.openweathermap.org/data/2.5/weather?id=2921044&units=metric&appid="$API_KEY
              response=$(curl -f "$url")
              status=$?
              if [ $status -eq 0 ]; then
                  echo $response > $FILE
                  echo "$FILE saved."
                  echo `date +"%Y%m%d"` >> ./docs/assets/data.txt
              else
                  echo "curl exit code: ($status) $response"
                  exit $status
              fi
          fi
          
      - name: git check in
        env:
          GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git config user.email "$GIT_OWNER_EMAIL"
          git config user.name "Sascha Greuel"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -a -m "add weather data"
            git remote rm origin
            git remote add origin https://softcreatr:$PUSH_TOKEN@github.com/softcreatr/historical-weather-data-germany.git
            git push origin HEAD:main
          else
            echo 'Nothing to do.'
          fi
