---
name: Repo Lock Down

on:
  issues:
    types: opened
  pull_request:
    types: opened

jobs:
  lockdown:
    runs-on: ubuntu-latest
    
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          issue-comment: >
            Thank you for your contribution, but this repository does not accept bug reports.
          skip-closed-issue-comment: true
          pr-comment: >
            Thank you for your contribution, but this repository does not accept pull requests.
          skip-closed-pr-comment: true
